version: '3.2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.0
    container_name: filebeat
    restart: always
    volumes:
      - type: bind
        source: ./filbeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
