version: '3'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      # publish_host 如果不写成hostname，会用错网卡，集群内就算同网络也无法通讯。
      # ping是可以ping通，但es监听的网卡是错的。
      # 或者可以先创建network,写死IP，使用macvlan网络
      - network.publish_host=es1
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - node.name=node-232
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es1,es2,es3
      - discovery.seed_hosts=es1,es2,es3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  e2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - network.publish_host=es2
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - node.name=node-231
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es1,es2,es3
      - discovery.seed_hosts=es1,es2,es3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - network.publish_host=elasticsearch3
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - node.name=node-230
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es1,es2,es3
      - discovery.seed_hosts=es1,es2,es3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.0
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - es1
      - es2
      - es3
    networks:
      - elk
    ports:
      - 4560:4560
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1


  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - /opt/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
    depends_on:
      - es1
      - es2
      - es3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1

networks:
  elk:
    driver: overlay
      #external:
    #name: elk