version: '3'
services:
  elasticsearch1:
    hostname: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      # publish_host 如果不写成hostname，会用错网卡，集群内就算同网络也无法通讯。
      # ping是可以ping通，但es监听的网卡是错的。
      # 或者可以先创建network,写死IP，使用macvlan网络
      - network.publish_host=elasticsearch1
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.port=9200
      - node.name=es1
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es1,es2,es3
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - node.role == worker
    elasticsearch2:
      hostname: elasticsearch2
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
      environment:
        - network.publish_host=elasticsearch2
        - network.host=0.0.0.0
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - http.port=9200
        - node.name=es2
        - cluster.name=es-cluster
        - cluster.initial_master_nodes=es1,es2,e3
        - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
      ports:
        - 9201:9200
      networks:
        - elk
      deploy:
        replicas: 1
#        placement:
#          constraints:
#            - node.role == worker
    elasticsearch3:
      hostname: elasticsearch3
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
      environment:
        - network.publish_host=elasticsearch3
        - network.host=0.0.0.0
        - http.cors.enabled=true
        - http.cors.allow-origin=*
        - http.port=9200
        - node.name=es3
        - cluster.name=es-cluster
        - cluster.initial_master_nodeses1,es2,e3
        - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Duser.timezone=GMT+08"
      ports:
        - 9203:9200
      networks:
        - elk
      deploy:
        replicas: 1
#        placement:
#          constraints:
#            - node.role == worker

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.9.0
#    volumes:
#      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    depends_on:
#      - es1
#      - es2
#      - es3
#    networks:
#      - elk
#    ports:
#      - 4560:4560
#    deploy:
#      replicas: 1
##      placement:
##        constraints:
##          - node.hostname == node1
#
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.9.0
#    ports:
#      - 5601:5601
#    networks:
#      - elk
#    volumes:
#      -  ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
#    depends_on:
#      - es1
#      - es2
#      - es3
#    deploy:
#      replicas: 1
##      placement:
##        constraints:
##          - node.hostname == node1

networks:
  elk:
    driver: overlay
      #external:
    #name: elk