version: '3.2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.0
    container_name: filebeat
    restart: always
    volumes:
     - ./filbeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    # needed to access all docker logs (read only) :
     - /var/lib/docker/containers/:/var/lib/docker/containers/
    # needed to access additional informations about containers
     - /var/run/docker.sock:/var/run/docker.sock:ro