server.name: kibana

server.host: "0.0.0.0"

elasticsearch.hosts: [ "http://elasticsearch1:9200","http://elasticsearch2:9200","http://elasticsearch3:9200" ]

xpack.monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.requestTimeout: 70000

i18n.locale: "zh-CN"

## X-Pack security credentials
#
elasticsearch.username: elastic

timelion.enabled: false
console.enabled: false
xpack.grokdebugger.enabled: false
xpack.searchprofiler.enabled: false
xpack.canvas.enabled: false
xpack.ml.enabled: false
xpack.infra.enabled: false
xpack.apm.enabled: false
xpack.graph.enabled: false