version: '3.2'

services:
  elasticsearch:
    image: 47.106.255.31:55000/ins/elasticsearch:7.9.0
    container_name: 'es'
    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/ins/jaeger/data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=node-232                   # 节点名称，集群模式下每个节点名称唯一
      - network.publish_host=10.0.0.232  # 用于集群内各机器间通信,其他机器访问本机器的es服务
      - network.host=0.0.0.0                # 设置绑定的ip地址，可以是ipv4或ipv6的，默认为0.0.0.0，
      - discovery.seed_hosts=10.0.0.232,10.0.0.233,10.0.0.234          # es7.x 之后新增的配置，写入候选主节点的设备地址，在开启服务后可以被选为主节点
      - cluster.initial_master_nodes=10.0.0.232,10.0.0.233,10.0.0.234  # es7.x 之后新增的配置，初始化一个新的集群时需要此配置来选举master
      - cluster.name=es-cluster     # 集群名称，相同名称为一个集群
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g -Duser.timezone=GMT+08"# 设置内存
    networks:
      - elk

#  logstash:
#    image: 47.106.255.31:55000/ins/logstash:7.9.0
#    volumes:
#      - type: bind
#        source: ./logstash/config/logstash.yml
#        target: /usr/share/logstash/config/logstash.yml
#        read_only: true
#      - type: bind
#        source: ./logstash/pipeline
#        target: /usr/share/logstash/pipeline
#        read_only: true
#    ports:
#      - "5044:5044"
#      - "5000:5000/tcp"
#      - "5000:5000/udp"
#      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

  kibana:
    image: 47.106.255.31:55000/ins/kibana:7.9.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk


networks:
  elk:
    driver: bridge

